version: '3.8'
services:
  planetsim:
    build: .
    image: planetsim:latest
    container_name: planetsim_app
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - .:/workspace
      - /tmp/.X11-unix:/tmp/.X11-unix
    network_mode: host
    tty: true
    stdin_open: true
